import Head from "next/head";

export default function Home() {
  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen flex items-center justify-center">
        <h3 className="text-xl font-bold">Hello Next</h3>
      </div>
    </main>
  )
}
